Implemented parameter support for measure evaluation
cqframework/clinical-reasoning pull request #363
Opened 2023-10-13 19:37 UTC by c-schuler

Fix for #334 

@dkayiwa please verify this resolves the issue you're seeing. I added a test that uses the data/artifacts you referenced in the issue.

2023-10-16 19:37 UTC, JPercival requested changes

2023-10-16 19:37 UTC, JPercival commented on cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/ANC/resources/library/library-ANCBaseConcepts.json
> +  "content": [ {
We're trying to reduce bloat in the repo by stripping away unneeded content/metadata for libraries. Check out the example here:
https://github.com/vitorpamplona/clinical-reasoning/blob/master/cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/FHIR347/resources/library/FHIR347.json

Notice that the content is now a reference to the CQL content. This means we don't have to do the base64 encode/decode while we're editing.

2023-10-16 21:11 UTC, JPercival commented on cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/ANC/resources/library/library-ANCBaseConcepts.json
> +  "content": [ {
There's a cqf-tooling operation to do that automatically here:
https://github.com/cqframework/cqf-tooling/pull/450

2023-11-03 17:43 UTC, JPercival commented on cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/ANC/resources/library/library-ANCBaseConcepts.json
> +  "content": [ {
I went ahead and did this.

2023-11-03 17:45 UTC, JPercival approved these changes

2023-11-03 18:45 UTC, Capt-Mac approved these changes

2023-11-03 19:36 UTC, merged