Update terminology client to use url param
cqframework/clinical-reasoning pull request #485
Opened 2024-06-27 22:19 UTC by TahaAttari

2024-06-27 22:24 UTC, TahaAttari commented on cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/client/TerminologyServerClientTest.java
> +        client.expand(vs, authoritativeSource, null, username, password);
these changes are to add a bit more coverage

2024-06-28 14:33 UTC, ibaisi commented on cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/client/TerminologyServerClient.java
> +        expansionParameters.addParameter("valueSetVersion", new org.hl7.fhir.r4.model.StringType(version));
maybe extract valueSetVersion to a const as it's used in many places?

2024-07-02 15:06 UTC, barhodes requested changes
My branch makes significant changes to this class.  Will need to discuss.

2024-07-03 00:00 UTC, TahaAttari commented
superseded by !488

2024-07-03 00:00 UTC, closed without merging